kind: ReplicaSet
apiVersion: apps/v1
metadata:
  namespace: nginx
  name: nginx-replicasets
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80


