kind: Service
apiVersion: v1
metadata:
  namespace: mysql
  name: mysql-service
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306


